Config = {}

Config.ESX_1_9_0 = true
Config.GetSharedObject = 'esx:getSharedObject'
-- [Config.EnableCommands]
-- Enables Commands Such As /char and /chardel
-- Config.EnableCommands = ESX.GetConfig().EnableDebug
Config.EnableCommands = true

-- EXPERIMENTAL Character Registration Method
Config.UseDeferrals = false



-- These values are for the second input validation in server/main.lua
Config.MaxNameLength = 20                            -- Max Name Length.
Config.MinHeight = 120                               -- 120 cm lowest height
Config.MaxHeight = 220                               -- 220 cm max height.
Config.LowestYear = 1900                             -- 112 years old is the oldest you can be.
Config.HighestYear = 2003                            -- 18 years old is the youngest you can be.

Config.FullCharDelete = true                         -- Delete all reference to character.
Config.EnableDebugging = ESX.GetConfig().EnableDebug -- prints for debugging :)

UIConfig = {
	["server_name"] = "ONE STORE",
	["server_slogan"] = 'ROLEPLAY',
	["server_logo"] = 'https://media.discordapp.net/attachments/1148964227118276658/1150534219005706250/SEFID.png',
	["registration"] = "Register Your Character",
	["welcome"] = "Welcome,",
	["male"] = "Male",
	["female"] = "Female",
	["firstname"] = "First Name",
	["lastname"] = "Last Name",
	["date_of_birth"] = "Birthday",
	["height"] = "Height",
	["register_bottum"] = "REGISTER",
	badWords = {
		"ahole",
		"anus",
		"ash0le",
		"ash0les",
		"asholes",
		"ass",
		"Ass Monkey",
		"Assface",
		"assh0le",
		"assh0lez",
		"asshole",
		"assholes",
		"assholz",
		"asswipe",
		"azzhole",
		"bassterds",
		"bastard",
		"bastards",
		"bastardz",
		"basterds",
		"basterdz",
		"Biatch",
		"bitch",
		"bitches",
		"Blow Job",
		"boffing",
		"butthole",
		"buttwipe",
		"c0ck",
		"c0cks",
		"c0k",
		"Carpet Muncher",
		"cawk",
		"cawks",
		"Clit",
		"cnts",
		"cntz",
		"cock",
		"cockhead",
		"cock-head",
		"cocks",
		"CockSucker",
		"cock-sucker",
		"crap",
		"cum",
		"cunt",
		"cunts",
		"cuntz",
		"dick",
		"dild0",
		"dild0s",
		"dildo",
		"dildos",
		"dilld0",
		"dilld0s",
		"dominatricks",
		"dominatrics",
		"dominatrix",
		"dyke",
		"enema",
		"f u c k",
		"f u c k e r",
		"fag",
		"fag1t",
		"faget",
		"fagg1t",
		"faggit",
		"faggot",
		"fagg0t",
		"fagit",
		"fags",
		"fagz",
		"faig",
		"faigs",
		"fart",
		"flipping the bird",
		"fuck",
		"fucker",
		"fuckin",
		"fucking",
		"fucks",
		"Fudge Packer",
		"fuk",
		"Fukah",
		"Fuken",
		"fuker",
		"Fukin",
		"Fukk",
		"Fukkah",
		"Fukken",
		"Fukker",
		"Fukkin",
		"g00k",
		"God-damned",
		"h00r",
		"h0ar",
		"h0re",
		"hells",
		"hoar",
		"hoor",
		"hoore",
		"jackoff",
		"jap",
		"japs",
		"jerk-off",
		"jisim",
		"jiss",
		"jizm",
		"jizz",
		"knob",
		"knobs",
		"knobz",
		"kunt",
		"kunts",
		"kuntz",
		"Lezzian",
		"Lipshits",
		"Lipshitz",
		"masochist",
		"masokist",
		"massterbait",
		"masstrbait",
		"masstrbate",
		"masterbaiter",
		"masterbate",
		"masterbates",
		"Motha Fucker",
		"Motha Fuker",
		"Motha Fukkah",
		"Motha Fukker",
		"Mother Fucker",
		"Mother Fukah",
		"Mother Fuker",
		"Mother Fukkah",
		"Mother Fukker",
		"mother-fucker",
		"Mutha Fucker",
		"Mutha Fukah",
		"Mutha Fuker",
		"Mutha Fukkah",
		"Mutha Fukker",
		"n1gr",
		"nastt",
		"nigger;",
		"nigur;",
		"niiger;",
		"niigr;",
		"orafis",
		"orgasim;",
		"orgasm",
		"orgasum",
		"oriface",
		"orifice",
		"orifiss",
		"packi",
		"packie",
		"packy",
		"paki",
		"pakie",
		"paky",
		"pecker",
		"peeenus",
		"peeenusss",
		"peenus",
		"peinus",
		"pen1s",
		"penas",
		"penis",
		"penis-breath",
		"penus",
		"penuus",
		"Phuc",
		"Phuck",
		"Phuk",
		"Phuker",
		"Phukker",
		"polac",
		"polack",
		"polak",
		"Poonani",
		"pr1c",
		"pr1ck",
		"pr1k",
		"pusse",
		"pussee",
		"pussy",
		"puuke",
		"puuker",
		"qweir",
		"recktum",
		"rectum",
		"retard",
		"sadist",
		"scank",
		"schlong",
		"screwing",
		"semen",
		"sex",
		"sexy",
		"Sh!t",
		"sh1t",
		"sh1ter",
		"sh1ts",
		"sh1tter",
		"sh1tz",
		"shit",
		"shits",
		"shitter",
		"Shitty",
		"Shity",
		"shitz",
		"Shyt",
		"Shyte",
		"Shytty",
		"Shyty",
		"skanck",
		"skank",
		"skankee",
		"skankey",
		"skanks",
		"Skanky",
		"slag",
		"slut",
		"sluts",
		"Slutty",
		"slutz",
		"son-of-a-bitch",
		"tit",
		"turd",
		"va1jina",
		"vag1na",
		"vagiina",
		"vagina",
		"vaj1na",
		"vajina",
		"vullva",
		"vulva",
		"w0p",
		"wh00r",
		"wh0re",
		"whore",
		"xrated",
		"xxx",
		"b!+ch",
		"bitch",
		"blowjob",
		"clit",
		"arschloch",
		"fuck",
		"shit",
		"ass",
		"asshole",
		"b!tch",
		"b17ch",
		"b1tch",
		"bastard",
		"bi+ch",
		"boiolas",
		"buceta",
		"c0ck",
		"cawk",
		"chink",
		"cipa",
		"clits",
		"cock",
		"cum",
		"cunt",
		"dildo",
		"dirsa",
		"ejakulate",
		"fatass",
		"fcuk",
		"fuk",
		"fux0r",
		"hoer",
		"hore",
		"jism",
		"kawk",
		"l3itch",
		"l3i+ch",
		"masturbate",
		"masterbat*",
		"masterbat3",
		"motherfucker",
		"s.o.b.",
		"mofo",
		"nazi",
		"nigga",
		"nigger",
		"nutsack",
		"phuck",
		"pimpis",
		"pusse",
		"pussy",
		"scrotum",
		"sh!t",
		"shemale",
		"shi+",
		"sh!+",
		"slut",
		"smut",
		"teets",
		"tits",
		"boobs",
		"b00bs",
		"teez",
		"testical",
		"testicle",
		"titt",
		"w00se",
		"jackoff",
		"wank",
		"whoar",
		"whore",
		"*damn",
		"*dyke",
		"*fuck*",
		"*shit*",
		"@$$",
		"amcik",
		"andskota",
		"arse*",
		"assrammer",
		"ayir",
		"bi7ch",
		"bitch*",
		"bollock*",
		"breasts",
		"butt-pirate",
		"cabron",
		"cazzo",
		"chraa",
		"chuj",
		"Cock*",
		"cunt*",
		"d4mn",
		"daygo",
		"dego",
		"dick*",
		"dike*",
		"dupa",
		"dziwka",
		"ejackulate",
		"Ekrem*",
		"Ekto",
		"enculer",
		"faen",
		"fag*",
		"fanculo",
		"fanny",
		"feces",
		"feg",
		"Felcher",
		"ficken",
		"fitt*",
		"Flikker",
		"foreskin",
		"Fotze",
		"Fu(*",
		"fuk*",
		"futkretzn",
		"gook",
		"guiena",
		"h0r",
		"h4x0r",
		"hell",
		"helvete",
		"hoer*",
		"honkey",
		"Huevon",
		"hui",
		"injun",
		"jizz",
		"kanker*",
		"kike",
		"klootzak",
		"kraut",
		"knulle",
		"kuk",
		"kuksuger",
		"Kurac",
		"kurwa",
		"kusi*",
		"kyrpa*",
		"lesbo",
		"mamhoon",
		"masturbat*",
		"merd*",
		"mibun",
		"monkleigh",
		"mouliewop",
		"muie",
		"mulkku",
		"muschi",
		"nazis",
		"nepesaurio",
		"nigger*",
		"orospu",
		"paska*",
		"perse",
		"picka",
		"pierdol*",
		"pillu*",
		"pimmel",
		"piss*",
		"pizda",
		"poontsee",
		"poop",
		"porn",
		"p0rn",
		"pr0n",
		"preteen",
		"pula",
		"pule",
		"puta",
		"puto",
		"qahbeh",
		"queef*",
		"rautenberg",
		"schaffer",
		"scheiss*",
		"schlampe",
		"schmuck",
		"screw",
		"sh!t*",
		"sharmuta",
		"sharmute",
		"shipal",
		"shiz",
		"skribz",
		"skurwysyn",
		"sphencter",
		"spic",
		"spierdalaj",
		"splooge",
		"suka",
		"b00b*",
		"testicle*",
		"titt*",
		"twat",
		"vittu",
		"wank*",
		"wetback*",
		"wichser",
		"wop*",
		"yed",
		"zabourah"
	}
}



Locale = {
		["show_active_character"] = "Show Active Character",
		["active_character"] = "Active Character: %s",
		["error_active_character"] = "There was an error obtaining your data.",
		["delete_character"] = "Delete Your Current Character.",
		["deleted_character"] = "Character Deleted",
		["error_delete_character"] = "There was a problem deleting your character.",
		["thank_you_for_registering"] = "Registration Successful. Enjoy!",
		["debug_xPlayer_get_first_name"] = "Returns Your First Name",
		["debug_xPlayer_get_last_name"] = "Returns Your Last Name",
		["debug_xPlayer_get_full_name"] = "Returns Your Full Name",
		["debug_xPlayer_get_sex"] = "Returns Your Sex",
		["debug_xPlayer_get_dob"] = "Returns Your DOB",
		["debug_xPlayer_get_height"] = "Returns Your Height",
		["error_debug_xPlayer_get_first_name"] = "There was an issue while obtaining your first name.",
		["error_debug_xPlayer_get_last_name"] = "There was an issue while obtaining your last name.",
		["error_debug_xPlayer_get_full_name"] = "There was an issue while obtaining your full name.",
		["error_debug_xPlayer_get_sex"] = "There was an issue while obtaining your sex.",
		["error_debug_xPlayer_get_dob"] = "There was an issue while obtaining your date of birth.",
		["error_debug_xPlayer_get_height"] = "There was an issue while obtaining your height.",
		["return_debug_xPlayer_get_first_name"] = "First Name: %s",
		["return_debug_xPlayer_get_last_name"] = "Last Name: %s",
		["return_debug_xPlayer_get_full_name"] = "Name: %s",
		["return_debug_xPlayer_get_sex"] = "Sex: %s",
		["return_debug_xPlayer_get_dob"] = "DOB: %s",
		["return_debug_xPlayer_get_height"] = "Height: %s Inches",
		["data_incorrect"] = "Invalid Data, Please try again.",
		["invalid_format"] = "Invalid Data Format, Please try again.",
		["no_identifier"] = "[ESX Identity]\nThere was an issue while loading your character!\nError Code: identifier-missing\n\nThis is caused by your identifier being missing. Please come back later or report this problem to the Server Owner.",
		["missing_identity"] = "[ESX Identity]\nThere was an issue loading your character!\nError Code: identity-missing\n\nIt seems like your identity is missing, try connecting again.",
		["deleted_identity"] = "Character deleted. Please rejoin to create a new character.",
		["already_registered"] = "You have already registered.",
		["invalid_firstname_format"] = "Invalid Format (First Name): Please try again.",
		["invalid_lastname_format"] = "Invalid Format (Last Name): Please try again.",
		["invalid_dob_format"] = "Invalid Format (DOB): Please try again.",
		["invalid_sex_format"] = "Invalid Format (Sex): Please try again.",
		["invalid_height_format"] = "Invalid Format (Height): Please try again.",
	  
}